name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        pip install pytest
        pip install pylint

    - name: Ejecutar pruebas
      run: |
        pytest

    - name: Analizar calidad del código
      run: |
        pylint calculadora.py